### ISSUE TITLE
Actually you need to fetch the value of name/description from the object, and update in the respective TextView

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-2---android-activity-alanantony24#2]
https://github.com/MAD11877/mad21-practical-2---android-activity-alanantony24/blob/d8b0a34a423e43ff24933d00585b12feaaae174c/app/src/main/java/sg/edu/np/practical2/MainActivity.java#L19

**Comment by alanantony24** [comment]
Resolved the issues....
